/**
 * AUTHORED opportunities for the demo bulletin — strategic interpretation
 * written by a strategist (here: authored fixture content), never
 * generated by the system. Each converges from currents by topic; at read
 * time getSurfaceBulletin resolves topics to whichever currents actually
 * derived, and an opportunity only renders when every topic it claims
 * convergence from produced a current.
 *
 * The narratives deliberately weave the cross-lens fixture story
 * (demand + conversation + behaviour + people) so the So What reads as
 * interpretation over corroborated evidence, not over a single source.
 */

export interface AuthoredOpportunity {
  slug: string
  title: string
  narrative: string
  /** Topics whose currents this opportunity converges from. */
  convergesFromTopics: string[]
}

export const AUTHORED_OPPORTUNITIES: AuthoredOpportunity[] = [
  {
    slug: 'own-home-charging',
    title: 'Own home charging before the market does',
    narrative:
      'The strongest converging story in the set: charging demand is ' +
      'accelerating while the conversation around it grows angrier, and 62% ' +
      'of EV intenders call charging availability their biggest barrier. The ' +
      'anxiety is real, unbranded, and most solvable at home — a bundled ' +
      'wallbox, installation and rebate-navigation offer would turn the ' +
      'category’s barrier into Audi’s first premium ownership moment, and ' +
      'blunt the PHEV hedge before it hardens.',
    convergesFromTopics: ['charging', 'hedge'],
  },
  {
    slug: 'answer-reliability-frustration',
    title: 'Answer the reliability frustration nobody owns',
    narrative:
      'Public-charging reliability is the loudest and most negative ' +
      'conversation in the category, and behaviour agrees — the network map ' +
      'and cost calculator keep climbing while sentiment sours. No brand ' +
      'owns the honest answer. A credible reliability layer — live ' +
      'availability, honest route planning, straight talk about queues — ' +
      'meets the frustration where it lives, in a voice no spec sheet ' +
      'reaches.',
    convergesFromTopics: ['charging'],
  },
  {
    slug: 'retell-the-badge',
    title: 'Retell the badge as engineering, not prestige',
    narrative:
      'The badge story is fading in every lens at once: model-name demand ' +
      'easing, owner talk quietening, model-page sessions down, and prestige ' +
      'under-indexing as a purchase driver — while a thin but fast challenger ' +
      'value signal forms underneath. Defending the price point means ' +
      'retelling the badge as engineering certainty — range delivered, ' +
      'charging solved — rather than social prestige.',
    convergesFromTopics: ['badge'],
  },
]
