/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'award-entries': AwardEntry;
    media: Media;
    videos: Video;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'award-entries': AwardEntriesSelect<false> | AwardEntriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  googleSub?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "award-entries".
 */
export interface AwardEntry {
  id: number;
  title: string;
  /**
   * e.g. Mumbrella, Cannes Lions, B&T
   */
  awardBody?: string | null;
  /**
   * e.g. Independent Agency of the Year
   */
  category?: string | null;
  year?: number | null;
  /**
   * Hides this page from the Pages list and disables its public URL (404). The record is retained — it is not deleted.
   */
  archived?: boolean | null;
  theme?: ('light' | 'dark') | null;
  layout?:
    | (
        | EntryHeroBlock
        | EntryCaseStudyBlock
        | EntryRichTextBlock
        | EntryMediaBlock
        | EntryResultsBlock
        | EntryQuoteBlock
        | EntryImageGridBlock
        | EntryVideoBlock
        | EntryButtonBlock
        | EntrySpacerBlock
        | EntryDividerBlock
      )[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EntryHeroBlock".
 */
export interface EntryHeroBlock {
  /**
   * Small text above headline (e.g. award body + year)
   */
  prehead?: string | null;
  headline: string;
  subhead?: string | null;
  media?: (number | null) | Media;
  /**
   * "Behind" adds a dark overlay so text stays readable
   */
  mediaPosition?: ('below' | 'behind' | 'above') | null;
  /**
   * Controls how much of the background image is visible
   */
  heroHeight?: ('compact' | 'standard' | 'tall' | 'full') | null;
  /**
   * Width of the image when above or below text
   */
  mediaWidth?: ('contained' | 'wide' | 'full') | null;
  textAlign?: ('center' | 'left') | null;
  /**
   * Ignored when image is behind (text forced to cream)
   */
  theme?: ('light' | 'dark' | 'plum') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'entryHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  uploadthingKey?: string | null;
  uploadthingUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EntryCaseStudyBlock".
 */
export interface EntryCaseStudyBlock {
  client?: string | null;
  headline: string;
  body?: string | null;
  resultColumns?: ('2' | '3') | null;
  results?:
    | {
        /**
         * e.g. 75.8%, $233M, 25.2%
         */
        value: string;
        /**
         * e.g. form completion rate
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  links?:
    | {
        /**
         * e.g. View live site, Read case study
         */
        label: string;
        /**
         * Full URL including https://
         */
        url: string;
        style?: ('outline' | 'text') | null;
        id?: string | null;
      }[]
    | null;
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  imageLayout?: ('auto' | '2-col' | '3-col' | 'stack') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'entryCaseStudy';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EntryRichTextBlock".
 */
export interface EntryRichTextBlock {
  richText: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  maxWidth?: ('narrow' | 'medium' | 'full') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'entryRichText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EntryMediaBlock".
 */
export interface EntryMediaBlock {
  media: number | Media;
  caption?: string | null;
  size?: ('default' | 'wide' | 'full') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'entryMedia';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EntryResultsBlock".
 */
export interface EntryResultsBlock {
  prehead?: string | null;
  headline?: string | null;
  intro?: string | null;
  columns?: ('2' | '3') | null;
  results: {
    value: string;
    label: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'entryResults';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EntryQuoteBlock".
 */
export interface EntryQuoteBlock {
  quote: string;
  author?: string | null;
  role?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'entryQuote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EntryImageGridBlock".
 */
export interface EntryImageGridBlock {
  images: {
    image: number | Media;
    caption?: string | null;
    id?: string | null;
  }[];
  columns?: ('auto' | '2' | '3') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'entryImageGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EntryVideoBlock".
 */
export interface EntryVideoBlock {
  prehead?: string | null;
  headline?: string | null;
  intro?: string | null;
  source: 'upload' | 'vimeo';
  video?: (number | null) | Video;
  videoUrl?: string | null;
  poster?: (number | null) | Media;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'entryVideo';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  sourceUploadthingKey?: string | null;
  sourceUploadthingUrl?: string | null;
  muxAssetId?: string | null;
  muxPlaybackId?: string | null;
  muxStatus?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EntryButtonBlock".
 */
export interface EntryButtonBlock {
  label: string;
  /**
   * Full URL including https://, or a relative URL starting with /
   */
  url: string;
  style?: ('outline' | 'text') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'entryButton';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EntrySpacerBlock".
 */
export interface EntrySpacerBlock {
  size: 'sm' | 'md' | 'lg';
  id?: string | null;
  blockName?: string | null;
  blockType: 'entrySpacer';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EntryDividerBlock".
 */
export interface EntryDividerBlock {
  color?: ('subtle' | 'red' | 'charcoal') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'entryDivider';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'award-entries';
        value: number | AwardEntry;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  googleSub?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "award-entries_select".
 */
export interface AwardEntriesSelect<T extends boolean = true> {
  title?: T;
  awardBody?: T;
  category?: T;
  year?: T;
  archived?: T;
  theme?: T;
  layout?:
    | T
    | {
        entryHero?: T | EntryHeroBlockSelect<T>;
        entryCaseStudy?: T | EntryCaseStudyBlockSelect<T>;
        entryRichText?: T | EntryRichTextBlockSelect<T>;
        entryMedia?: T | EntryMediaBlockSelect<T>;
        entryResults?: T | EntryResultsBlockSelect<T>;
        entryQuote?: T | EntryQuoteBlockSelect<T>;
        entryImageGrid?: T | EntryImageGridBlockSelect<T>;
        entryVideo?: T | EntryVideoBlockSelect<T>;
        entryButton?: T | EntryButtonBlockSelect<T>;
        entrySpacer?: T | EntrySpacerBlockSelect<T>;
        entryDivider?: T | EntryDividerBlockSelect<T>;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EntryHeroBlock_select".
 */
export interface EntryHeroBlockSelect<T extends boolean = true> {
  prehead?: T;
  headline?: T;
  subhead?: T;
  media?: T;
  mediaPosition?: T;
  heroHeight?: T;
  mediaWidth?: T;
  textAlign?: T;
  theme?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EntryCaseStudyBlock_select".
 */
export interface EntryCaseStudyBlockSelect<T extends boolean = true> {
  client?: T;
  headline?: T;
  body?: T;
  resultColumns?: T;
  results?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  links?:
    | T
    | {
        label?: T;
        url?: T;
        style?: T;
        id?: T;
      };
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  imageLayout?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EntryRichTextBlock_select".
 */
export interface EntryRichTextBlockSelect<T extends boolean = true> {
  richText?: T;
  maxWidth?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EntryMediaBlock_select".
 */
export interface EntryMediaBlockSelect<T extends boolean = true> {
  media?: T;
  caption?: T;
  size?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EntryResultsBlock_select".
 */
export interface EntryResultsBlockSelect<T extends boolean = true> {
  prehead?: T;
  headline?: T;
  intro?: T;
  columns?: T;
  results?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EntryQuoteBlock_select".
 */
export interface EntryQuoteBlockSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  role?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EntryImageGridBlock_select".
 */
export interface EntryImageGridBlockSelect<T extends boolean = true> {
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  columns?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EntryVideoBlock_select".
 */
export interface EntryVideoBlockSelect<T extends boolean = true> {
  prehead?: T;
  headline?: T;
  intro?: T;
  source?: T;
  video?: T;
  videoUrl?: T;
  poster?: T;
  caption?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EntryButtonBlock_select".
 */
export interface EntryButtonBlockSelect<T extends boolean = true> {
  label?: T;
  url?: T;
  style?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EntrySpacerBlock_select".
 */
export interface EntrySpacerBlockSelect<T extends boolean = true> {
  size?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EntryDividerBlock_select".
 */
export interface EntryDividerBlockSelect<T extends boolean = true> {
  color?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  uploadthingKey?: T;
  uploadthingUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  sourceUploadthingKey?: T;
  sourceUploadthingUrl?: T;
  muxAssetId?: T;
  muxPlaybackId?: T;
  muxStatus?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}